### ISSUE TITLE
Gau and Hakrawler changes their options

### ISSUE THREAD

**Issue by fajarslvn** [w9w/JSA#10]
There's several changes on gau and hakrawler options, So it needs update on automation.sh script

**Comment by w9w** [comment]
Hi @fajarslvn! Thank you for creating an issue request. These are indeed giving errors on the latest versions. I removed -user-agent option from gau, corrected options for hakrawler, and made it work through grep. I consider the issue fixed now - everything works fine.

If experience an issue - please create another issue or comment on the current.

Thank you,
Max
