### ISSUE TITLE
Missing tldextract python module

### ISSUE THREAD

**Issue by yassineaboukir** [w9w/JSA#4]
Looks like the `tldextract` python module was not covered in the bash installation file which causes this error when initiating the automation:

```
Searching for URLs in GH..
Traceback (most recent call last):
  File "github-endpoints.py", line 234, in <module>
    import tldextract
ModuleNotFoundError: No module named 'tldextract'
```

I believe the following PR https://github.com/w9w/JSA/pull/3 should fix it.

**Comment by w9w** [comment]
I accepted PR, thanks! Closing now.
