### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by hakyyyy** [w9w/JSA#5]
hy 
i have facing problem in installation 
when i used command  echo " https://example.com/" | subjs | python3 jsa.py  then its not work 
and use only python3 jsa.py then its work but not 1st level 2nd level normal page identifier not js file 

i tried install automation so i did all the things but when you said use your github api to .token so i can't understand how to do that so my ,/automation.sh is also not working 

so please make a video how to install

**Comment by w9w** [comment]
Hi, what errors are you getting now when executing jsa.py and automation.sh?

**Comment by hakyyyy** [comment]
when i used command echo " https://example.com/" | subjs | python3 jsa.py then its not work

i think i m not properly installed so please make a video how to install.

**Comment by w9w** [comment]
@hakyyyy, there wasn't enough information to help you. Everything works for me on Ubuntu and macOS after the proper installation. I'm closing the issue.
