### ISSUE TITLE
Issue with grep

### ISSUE THREAD

**Issue by Sicks3c** [w9w/JSA#9]
## Summary

Hello Team

Thank you for the great tool
It appears that there's an issue with grep I couldn't figure it out
Followed the instalation process step by step
Here's t he issue
<img width="743" alt="Screen Shot 2021-10-20 at 12 19 33" src="https://user-images.githubusercontent.com/32225186/138083555-1c413916-9e4f-4d15-bab3-0f76758c7025.png">

Regards

**Comment by w9w** [comment]
Hi @Sicks3c! I just checked and everything works fine on Ubuntu:

![image](https://user-images.githubusercontent.com/38838852/139641451-df19b655-cb57-49ba-b3ab-15765ee7877f.png)

What OS are you using?

**Comment by Sicks3c** [comment]
Hello

I'm using it in Mac OS, which should have the same behavior

Regards

**Comment by fajarslvn** [comment]
I got the same problem too on mac

**Comment by fajarslvn** [comment]
> Hello
> 
> I'm using it in Mac OS, which should have the same behavior
> 
> Regards

I got the same problem too on mac

**Comment by w9w** [comment]
Hi @Sicks3c @fajarslvn! I tried to use both .py and .sh on macOS where the OS and grep are the latest versions and everything works perfectly - I haven't got a single error. Consider updating software - an error should disappear. If it's not - please let me know in a separate issue request or by leaving a comment here.

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/38838852/162488807-fc077fb2-ddd7-4ebf-9bf9-7dda77c3e361.png">

Best regards,
Max (@w2w).

**Comment by Sicks3c** [comment]
Hi @w9w 

I'm not sure why it doesn't work for us as its intended
here's my output for the same command
<img width="663" alt="Screen Shot 2022-04-08 at 23 50 57" src="https://user-images.githubusercontent.com/32225186/162547480-31a35a3a-7c3a-425d-8bea-e25a628e4e5f.png">

**Comment by w9w** [comment]
@Sicks3c, are you sure you proceeded through the installation process including `mkdir tmp` correctly?

Try `printf 'https://hackerone.com' | subjs | tee tmp/1234.txt` and paste here the output.

**Comment by w9w** [comment]
I am archiving this one due to inactivity.
